In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Task 1

## Explore Data

In [28]:
df_1 = pd.read_csv('./Dataset .csv')

In [29]:
df_1.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [30]:
df_1.shape

(9551, 21)

In [31]:
df_1['Restaurant ID'].unique().shape

(9551,)

## Preprocessing

In [32]:
df_1.drop_duplicates(inplace=True)

In [33]:
df_1.drop(['Restaurant ID', 'Restaurant Name'], axis=1, inplace=True)

In [35]:
df_1.isna().sum()

Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [37]:
df_1.dropna(inplace=True)

In [38]:
from sklearn.preprocessing import LabelEncoder

for col in df_1.columns:
    if df_1[col].dtype == 'object':
        le = LabelEncoder()
        df_1[col] = le.fit_transform(df_1[col])

In [39]:
df_1

,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,162,73,8677,171,172,121.027535,14.565443,920,1100,0,1,0,0,0,3,4.8,0,1,314
1,162,73,6047,592,600,121.014101,14.553708,1111,1200,0,1,0,0,0,3,4.5,0,1,591
2,162,75,4676,308,314,121.056831,14.581404,1671,4000,0,1,0,0,0,4,4.4,1,5,270
3,162,75,8682,860,873,121.056475,14.585318,1126,1500,0,0,0,0,0,4,4.9,0,1,365
4,162,75,8681,860,873,121.057508,14.584450,1122,1500,0,1,0,0,0,4,4.8,0,1,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,208,139,5918,516,522,28.977392,41.022793,1813,80,11,0,0,0,0,3,4.1,1,5,788
9547,208,139,5954,551,557,29.041297,41.009847,1824,105,11,0,0,0,0,3,4.2,1,5,1034
9548,208,139,5958,553,560,29.034640,41.055817,1110,170,11,0,0,0,0,4,3.7,5,2,661
9549,208,139,5959,553,560,29.036019,41.057979,1657,120,11,0,0,0,0,4,4.0,1,5,901
9550,208,139,4250,668,679,29.026016,40.984776,331,55,11,0,0,0,0,2,4.0,1,5,591

## Data Spliting

In [43]:
from sklearn.model_selection import train_test_split

X = df_1.drop('Aggregate rating', axis=1)
y = df_1['Aggregate rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)

rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [45]:
from sklearn.metrics import mean_squared_error, r2_score

y_pred = rf.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 0.02926880565741225
R-squared: 0.9872190418794761

## Get the most features affect on the rating

In [46]:
feature_importances = rf.feature_importances_

feature_importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': feature_importances
})

feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

print("Feature importances:\n", feature_importance_df)

Feature importances:
                  Feature  Importance
17                 Votes    0.899958
15          Rating color    0.083618
16           Rating text    0.005265
6               Latitude    0.002061
5              Longitude    0.001902
2                Address    0.001872
7               Cuisines    0.001818
8   Average Cost for two    0.001140
3               Locality    0.000766
4       Locality Verbose    0.000742
11   Has Online delivery    0.000288
1                   City    0.000239
14           Price range    0.000169
10     Has Table booking    0.000081
12     Is delivering now    0.000031
9               Currency    0.000026
0           Country Code    0.000023
13  Switch to order menu    0.000000